### ISSUE TITLE
Server installation in docker?

### ISSUE THREAD

**Issue by martin-arg** [lynxaegon/obsidian-anysocket-sync-server#1]
Is there any possibility to install the server as a docker?

**Comment by lynxaegon** [comment]
At the moment there is no docker setup, but i'll make it in the next days

**Comment by martin-arg** [comment]
thanks

**Comment by lynxaegon** [comment]
I have added a setup for docker, you can check it out [here](https://github.com/lynxaegon/obsidian-anysocket-sync-server?tab=readme-ov-file#docker-setup)

**Comment by s39n** [comment]
I have Docker running and all devices are connected!, thank for making this!
here is my compose file for refreance
```
version: '3'
services:
  obsidian-sync-server:
    image: lynxaegon/obsidian-anysocket-sync-server
    container_name: obsidian_sync_server
    ports:
      - "3758:3000"
    volumes:
      - /share/Docker/AnySocket/config.js:/app/config.js
      - /share/Docker/AnySocket/data:/app/data
    restart: unless-stopped
```
